blog/urls.py
from django.urls import path, re_path
from . import views
app_name = 'blog'
urlpatterns = [
    path('blog/', views.blog, name='blog'),

    re_path(r'^detail/(?P<slug>[^/]+)/?$',
            views.blog_detail, name='blog_detail'),
]

contact/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from .views import ServicesDetails
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('clients/', views.clients, name='clients'),

    path('services/', views.services, name='services'),
    path('FAQ/', views.faq, name='faq'),
    path('careers/', views.career, name='career'),
    path('services/<str:service_type>/',
         ServicesDetails.as_view(), name='service_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('booking.urls', namespace='booking')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('contact.urls', namespace='contact')),
   
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/layouts/footer.html
{% load static %}
<footer class="pt-5 pb-5 sm-pt-40px sm-pb-45px footer-dark bg-extra-medium-slate-blue">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <!-- start footer column -->
            <div class="col-lg-3 col-sm-6 last-paragraph-no-margin order-5 order-sm-4 order-lg-1 text-center text-sm-start">
                <a href="{% url 'home:home' %}" class="footer-logo mb-15px d-block d-lg-inline-block"><img src="{% static 'assets/images/bsafe/bsafe_logo.png'%}" /></a>

                <p>
                    Copyright &COPY; 2021
                    <a href="{% url 'home:home' %}" target="_blank" class="text-white text-decoration-line-bottom">Powered By BsafeGroup</a>
                </p>
            </div>
            <!-- end footer column -->
            <!-- start footer column -->
            <div class="col-4 col-lg-2 col-sm-4 md-mb-50px sm-mb-30px order-1 order-lg-2">
                <span class="alt-font d-block text-white mb-5px">Company</span>
                <ul>
                    <li><a href="{% url 'home:about' %}">About Us</a></li>
                    <li><a href="{% url 'home:services' %}">Our Services</a></li>
                    <li><a href="{% url 'home:clients' %}">Our Clients</a></li>
                    <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                </ul>
            </div>
            <!-- end footer column -->
            <!-- start footer column -->
            <div class="col-7 col-lg-2 col-sm-4 md-mb-50px sm-mb-30px order-2 order-lg-3 px-lg-2">
                <span class="alt-font d-block text-white mb-5px">Services</span>
                <ul>
                    <li>
                        <a href="{% url 'home:service_detail' service_type='HSEQ_management' %}">HSEQ Management</a>
                    </li>
                    <li>
                        <a href="{% url 'home:service_detail' service_type='HSE_deployment' %}">HSE Deployment</a>
                    </li>
                    <li>
                        <a href="{% url 'home:service_detail' service_type='HSE_Field_Trainings' %}">HSE Field Trainings</a>
                    </li>
                    <li>
                        <a href="{% url 'home:service_detail' service_type='construction_management' %}">Construction Management
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'home:service_detail' service_type='website_applications' %}">Web Applications</a>
                    </li>
                    <li>
                        <a href="{% url 'home:service_detail' service_type='Marketing_Branding' %}">
                            Design Renovation
                        </a>
                    </li>
                    <li><a href="{% url 'home:service_detail' service_type='Thesis_Guidance' %}">Thesis Guidance</a></li>
                    <li><a href="{% url 'home:service_detail' service_type='Import_Export' %}">Import & Export</a></li>
                    <li><a href="{% url 'home:service_detail' service_type='Logistics_Transport' %}">Logistics and transport</a></li>
                    <li><a href="{% url 'home:service_detail' service_type='Food_Safety' %}">Food Safety & Hygiene</a></li>
                </ul>
            </div>
            <!-- end footer column -->
            <!-- start footer column -->
            <div class="col-5 col-lg-2 col-sm-4 md-mb-50px sm-mb-30px order-3 order-lg-4">
                <span class="alt-font d-block text-white mb-5px">Social connect</span>
                <ul>
                    <li>
                        <a href="https://maps.app.goo.gl/HbGzhFAc6SPNkXtq5"
                            target="_blank">Google Maps</a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/bsafegroup/" target="_blank">Facebook</a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/company/98545009" target="_blank">LinkedIn</a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/channel/UCEQGp-C3C1ocodfSstzC13g" target="_blank">Youtube</a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/bsafegroup/" target="_blank">Instagram</a>
                    </li>
                    <li><a href="https://x.com/BsafeintlEU" target="_blank">X</a></li>
                    <li><a href="https://www.tiktok.com/@bsafegroup" target="_blank">Tiktok</a></li>

                </ul>
            </div>
            <!-- end footer column -->
            <!-- start footer column -->
            <div class="col-7 col-lg-3 col-sm-6 xs-mb-30px last-paragraph-no-margin order-4 order-sm-5 order-lg-5">
                <span class="alt-font d-block text-white mb-5px">Get in touch</span>
                <p class="w-80 lg-w-100 md-w-70 sm-w-100 mb-10px">
                    Our Regional Service Areas
                </p>
                <div>
                    <i class="feather icon-feather-phone-call icon-very-small text-white me-10px"></i><a href="tel:+32033861949" class="text-white">+32 033 8619 49</a>
                </div>

                <div>
                    <i class="feather icon-feather-mail icon-very-small text-white me-10px"></i><a href="mailto:info@bsafegroup.eu" class="text-white text-decoration-line-bottom">info@bsafegroup.eu</a>
                </div>

            </div>
            <!-- end footer column -->
        </div>
    </div>
</footer>


</div>
<!-- end footer column -->
</div>
</div>
</footer>

templates/layouts/navigation.html
{% load static %}

<header>

    <nav class="navbar navbar-expand-lg header-transparent bg-transparent disable-fixed" data-header-hover="dark">
        <div class="container-fluid">
            <div class="col-lg-6 col-3 me-lg-0 me-auto d-flex d-lg-flex">
                <div class="header-icon">
                    <div class="header-social-icon icon">
                        <a href="https://www.facebook.com/profile.php?id=61566862343062" target="_blank"><i class="fa-brands  fa-facebook-f sm-fs-15 text-white-linear"></i></a>
                        <a href="https://www.linkedin.com/company/www-bsafegroup-eu/posts/?feedView=all" target="_blank"><i class="fa-brands fa-linkedin sm-fs-15 text-white-linear"></i></a>
                        <a href="https://www.youtube.com/@BSafeGroup" target="_blank"><i class="fa-brands fa-youtube sm-fs-15 text-white-linear"></i></a>
                        <a href="https://www.instagram.com/bsafegroup.be/" target="_blank"><i class="fa-brands fa-instagram sm-fs-15 text-white-linear"></i></a>
                        <a href="https://x.com/bsafegroup2022" target="_blank"><i class="fa-brands sm-fs-15 fa-x text-white-linear "></i></a>
                        <a href="https://www.tiktok.com/@bsafegroup" target="_blank"><i class="fa-brands sm-fs-15 fa-tiktok text-white-linear "></i></a>

                    </div>
                </div>
            </div>
            <div class="col-auto">
                <a class="navbar-brand" href="demo-horizontal-portfolio.html">
                    <img data-at2x="images/demo-horizontal-portfolio-logo@2x.png" alt="" class="default-logo">
                    <img  data-at2x="images/demo-horizontal-portfolio-logo@2x.png" alt="" class="alt-logo">
                    <img data-at2x="images/demo-horizontal-portfolio-logo@2x.png" alt="" class="mobile-logo">
                </a>
            </div>
            <div class="col-auto col-lg-6 text-end">

                <div class="header-icon header-push-button d-flex hamburger-push-button icon">
                    <div class="header-button me-15px">
                        <a href="{% url 'contact:contact' %}"><button class="btn btn-small bg-base-color text-white btn-rounded">
                                Where to start
                            </button></a>
                    </div>
                    <div class="push-button">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div class="push-menu hamburger-nav header-dark hamburger-menu-simple bg-black" style="background-image: url(images/vertical-line-bg-small-light-gray.svg)">
        <span class="close-menu text-dark-gray bg-white fs-18"><i class="fa-solid fa-xmark"></i></span>
        <div class="d-flex flex-column align-items-center justify-content-center h-100 p-5 lg-p-7 sm-px-0">
            <a class="hamburger-logo" href="demo-horizontal-portfolio.html">
                <img src="images/demo-horizontal-portfolio-logo.png" data-at2x="images/demo-horizontal-portfolio-logo@2x.png" alt="">
            </a>
            <div class="row align-items-center justify-content-center">
                <div class="hamburger-menu menu-list-wrapper col-lg-5 lg-no-margin offset-lg-1" data-scroll-options='{ "theme": "light" }'>
                    <ul class="menu-item-list fw-500 alt-font text-center text-lg-start">
                        <li class="menu-item"><a href="{% url 'home:home' %}" class="nav-link">Home</a></li>
                        <li class="menu-item"><a href="{% url 'home:about' %}" class="nav-link">About</a></li>
                        <li class="menu-item dropdown">
                            <a class="nav-link " href="{%url 'home:services' %}" id="navbarDropdown" role="button" data-bs-toggle="" aria-expanded="">
                                Services
                            </a>
                            <!-- <ul class="dropdown-menu z-index-3 position-relative mb-5 pb-20px" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='HSEQ_management' %}">HSEQ Management</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='HSE_deployment' %}">HSE Deployment</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='HSE_Field_Trainings' %}">HSE Field Trainings</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='construction_management' %}">Construction Supervision</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='website_applications' %}">Web Applications</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='Marketing_Branding' %}">Branding & Marketing</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='Thesis_Guidance' %}">Thesis Guidance</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:service_detail' service_type='Import_Export' %}">Import & Export</a></li>
                            </ul> -->
                        </li>
                        <li class="menu-item"><a href="{% url 'home:clients' %}" class="nav-link">Clients</a></li>
                        <li class="menu-item"><a href="{% url 'blog:blog' %}" class="nav-link">Blog</a></li>
                        <li class="menu-item"><a href="{% url 'home:faq' %}" class="nav-link">FAQ</a></li>
                        <li class="menu-item"><a href="{% url 'contact:contact' %}" class="nav-link">Contact</a></li>
                        <li class="menu-item"><a href="{% url 'home:career' %}" class="nav-link">Careers</a></li>
                        <li class="menu-item"><a href="{% url 'home:about' %}#team" class="nav-link">Team</a></li>

                        <div class="col-12 d-flex d-lg-none  elements-social social-icon-style-10">
                            <ul class="light">
                                <li class="me-15px">
                                    <a class="facebook" href="https://www.facebook.com/profile.php?id=61566862343062" target="_blank">Fb.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="instagram" href="https://www.instagram.com/bsafegroup.be/" target="_blank">Ig.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="twitter" href="https://www.linkedin.com/company/www-bsafegroup-eu/posts/?feedView=all" target="_blank">Ln.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="behance" href="https://www.youtube.com/@BSafeGroup" target="_blank">Yb.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="behance" href="https://x.com/bsafegroup2022" target="_blank">X.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="behance" href="https://www.tiktok.com/@bsafegroup" target="_blank">TK.</a>
                                </li>
                                <li>
                                    <a class="behance" href="https://www.pinterest.com/bsafegroupbe/" target="_blank">Pt.</a>
                                </li>
                            </ul>
                        </div>

                    </ul>
                </div>
                <div class="col-xl-4 col-lg-4 d-none d-lg-inline-block offset-xl-1 offset-lg-1">
                    <div class="row menu-address">
                        <div class="col-12 mb-40px">
                            <span class="text-white fw-500 mb-5px d-block">Direct Contact</span>
                            <div class="d-block">
                                <span>Whatsapp:</span> <a href="https://wa.me/+31645300279"><i class="fa-brands fa-whatsapp me-10px"></i>+31 645300279</a>
                            </div>
                            <div class="d-block">
                                <span>Mobile:</span> <a href="tel:+3223184169"><i class="fa-solid fa-phone me-10px"></i>+32 23184169</a>
                            </div>
                            <div class="d-block">
                                <span>Email:</span> <a href="mailto:info@bsafegroup.eu">info@bsafegroup.eu</a>
                            </div>
                        </div>
                        <div class="col-12 last-paragraph-no-margin mb-40px">
                            <span class="text-white fw-500 mb-5px d-block">Contact Address</span>
                            <p class="mb-10px">Belguim - Brussels & Flanders</p>
                            <p class="ps-3 mb-0">- Pl. Adolphe Sax, 1050 Ixelles - Brussels 1050 <br>- Vrasenestraat, 9100 Sint-Niklaas - Flanders 9100</p>
                            <p class="mb-10px">Latvia - Rega</p>
                            <p class=" ps-3 mb-0">- Stockmann, 13. janvāra iela 8, 3rd floor</p>

                        </div>
                        <div class="col-12 elements-social social-icon-style-10">
                            <ul class="light">
                                <li class="me-15px">
                                    <a class="facebook" href="https://www.facebook.com/profile.php?id=61566862343062" target="_blank">Fb.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="instagram" href="https://www.instagram.com/bsafegroup.be/" target="_blank">Ig.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="twitter" href="https://www.linkedin.com/company/www-bsafegroup-eu/posts/?feedView=all" target="_blank">Ln.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="behance" href="https://www.youtube.com/@BSafeGroup" target="_blank">Yb.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="behance" href="https://x.com/bsafegroup2022" target="_blank">X.</a>
                                </li>
                                <li class="me-15px">
                                    <a class="behance" href="https://www.tiktok.com/@bsafegroup" target="_blank">TK.</a>
                                </li>
                                <li>
                                    <a class="behance" href="https://www.pinterest.com/bsafegroupbe/" target="_blank">Pt.</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</header>

templates/layouts/scripts.html
{% load static %}

<script src="{% static 'assets/js/jquery.js'%}"></script>
<script src="{% static 'assets/js/vendors.min.js'%}"></script>
<script src="{% static 'assets/js/main.js'%}"></script>
<script type="text/javascript" src="{% static 'assets/js/booking-modal-handler.js'%}"></script>