blog/urls.py
from django.urls import path, re_path
from . import views
app_name = 'blog'
urlpatterns = [
    path('blog/', views.blog, name='blog'),

    re_path(r'^detail/(?P<slug>[^/]+)/?$',
            views.blog_detail, name='blog_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('booking.urls', namespace='booking')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('contact.urls', namespace='contact')),
   
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from .utils import code_generator, create_shortcode
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Categories(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    title = models.CharField(max_length=500)
    subtitle = models.CharField(max_length=600, blank=True, null=True)
    image = models.ImageField(
        upload_to='blog/posts/', verbose_name=_("Post Image"), blank=True, null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    content = models.TextField(blank=True, null=True,
                             verbose_name=_("Content"))
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    post_Slug = models.SlugField(max_length=500,
                                 blank=True, null=True, allow_unicode=True, unique=True, verbose_name=_("Slugfiy"))

    def __str__(self):

        return str(self.title)

    # def save(self, *args, **kwargs):
    #     if not self.post_Slug:
    #         self.post_Slug = slugify(self.title)
    #     super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:postdetail', kwargs={'slug': self.post_Slug})


def pre_save_post_receiver(sender, instance, *args, **kwargs):

    if not instance.post_Slug or instance.post_Slug is None or instance.post_Slug == "":
        instance.post_Slug = slugify(instance.title, allow_unicode=True)
        qs_exists = BlogPost.objects.filter(
            post_Slug=instance.post_Slug).exists()
        if qs_exists:
            instance.post_Slug = create_shortcode(instance)


pre_save.connect(pre_save_post_receiver, sender=BlogPost)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost, Categories


def blog(request):
    category_id = request.GET.get('category')

    if category_id:
        all_posts = BlogPost.objects.filter(
            category_id=category_id).order_by('-date')
    else:
        all_posts = BlogPost.objects.all().order_by('-date')
    latest_posts = all_posts[:3]
    categories = Categories.objects.all()

    return render(request, 'blog/blog.html', {
        'all_posts': all_posts,
        'latest_posts': latest_posts,
        'categories': categories,
        'selected_category': category_id,
    })


def blog_detail(request, slug):
    post = get_object_or_404(BlogPost, post_Slug=slug)
    return render(request, 'blog/blog_detail.html', {'post': post})

blog/templates/blog/blog.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="page-title-big-typography bg-dark-gray ipad-top-space-margin" data-parallax-background-ratio="0.5" style="background-image: url(/static/assets/images/bsafe/blog-banner.jpg)"> <!-- img size 1920*1100-->
    <div class="opacity-extra-medium bg-dark-slate-blue"></div>
    <div class="container">
        <div class="row align-items-center justify-content-center extra-small-screen">
            <div class="col-12 position-relative text-center page-title-extra-large">
                <h1 class="m-auto text-white text-shadow-double-large fw-500 ls-minus-3px xs-ls-minus-2px" data-anime='{ "translateY": [15, 0], "opacity": [0,1], "duration": 600, "delay": 0, "staggervalue": 300, "easing": "easeOutQuad" }'>It Makes The Difference</h1>
            </div>
            <div class="down-section text-center" data-anime='{ "translateY": [-15, 0], "opacity": [0,1], "duration": 600, "delay": 0, "staggervalue": 300, "easing": "easeOutQuad" }'>
                <a href="#down-section" aria-label="scroll down" class="section-link">
                    <div class="d-flex justify-content-center align-items-center mx-auto rounded-circle fs-30 text-white">
                        <i class="feather icon-feather-chevron-down"></i>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

<section class="p-0"></section>
<div class="container">
    <div class="row mt-7">
        <div class="col-lg-5 md-mb-35px">
            <h2 class="text-dark-gray fw-600 mb-10 ls-minus-2px md-mb-0">Popular Articles</h2>

        </div>
        <div class="col-lg-6 offset-lg-1">
            <ul class="popular-post-sidebar position-relative" data-anime='{ "el": "childs", "translateY": [15, 0], "opacity": [0,1], "duration": 800, "delay": 200, "staggervalue": 300, "easing": "easeOutQuad" }'>
                {% for post in latest_posts %}
                <li class="d-sm-flex align-items-center mb-35px">
                    <figure>
                        <a href="{% url 'blog:blog_detail' post.post_Slug %}"><img src="{{ post.image.url }}" class="border-radius-4px" alt="{{ post.title }}"></a>
                    </figure>
                    <div class="col media-body">
                        <a href="{% url 'blog:blog_detail' post.post_Slug %}" class="fw-600 fs-22 lh-30 ls-minus-05px text-dark-gray text-dark-gray-hover d-inline-block mb-15px w-85 xl-w-100">{{ post.title }}</a>
                        <div>
                            <a href="{% url 'blog:blog_detail' post.post_Slug %}" class="d-inline-block fs-14 fw-700 text-uppercase text-dark-gray text-dark-gray-hover">{{ post.category.name }}</a>
                            <span class="d-inline-block fs-10 alt-font align-middle opacity-7 ms-5px me-5px">•</span>
                            <a href="#" class="d-inline-block fs-14 text-uppercase fw-500 text-medium-gray-hover">{{ post.date }}</a>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
</section>

<section id="down-section">
    <div class="container">
        <div class="row">
            <div class="col-12 px-0">
                <ul class="blog-classic blog-wrapper grid-loading grid grid-4col xl-grid-4col lg-grid-3col md-grid-2col sm-grid-2col xs-grid-1col gutter-double-extra-large"
                    data-anime='{ "el": "childs", "translateY": [50, 0], "opacity": [0,1], "duration": 1200, "delay": 0, "staggervalue": 150, "easing": "easeOutQuad" }'>
                    <li class="grid-sizer"></li>

                    {% for post in all_posts %}
                    <li class="grid-item {{ post.category.name|lower }}">
                        <div class="card bg-transparent border-0 h-100">
                            <div class="blog-image position-relative overflow-hidden border-radius-4px">
                                <a href="{% url 'blog:blog_detail' post.post_Slug %}">
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                                </a>
                            </div>
                            <div class="card-body px-0 pt-30px pb-30px xs-pb-15px">
                                <span class="fs-14 text-uppercase d-block mb-5px fw-500">
                                    <a href="#" class="text-dark-gray text-dark-gray-hover fw-700 categories-text ">{{ post.category.name }}</a>
                                    <a href="#" class="blog-date text-medium-gray-hover">{{ post.date }}</a>
                                </span>
                                <a href="{% url 'blog:blog_detail' post.post_Slug %}" class="card-title fw-600 fs-17 lh-28 text-dark-gray text-dark-gray-hover d-inline-block w-95 sm-w-100">
                                    {{ post.title }}
                                </a>
                            </div>
                        </div>
                    </li>
                    {% endfor %}


                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mt-2 d-flex justify-content-center">

                <ul class="pagination pagination-style-01 fs-13 fw-500 mb-0" data-anime='{ "translate": [0, 0], "opacity": [0,1], "duration": 600, "delay": 100, "staggervalue": 150, "easing": "easeOutQuad" }'>
                    <li class="page-item"><a class="page-link" href="#"><i class="feather icon-feather-arrow-left fs-18 d-xs-none"></i></a></li>
                    <li class="page-item"><a class="page-link" href="#">01</a></li>
                    <li class="page-item active"><a class="page-link" href="#">02</a></li>
                    <li class="page-item"><a class="page-link" href="#">03</a></li>
                    <li class="page-item"><a class="page-link" href="#">04</a></li>
                    <li class="page-item"><a class="page-link" href="#"><i class="feather icon-feather-arrow-right fs-18 d-xs-none"></i></a></li>
                </ul>

            </div>
        </div>
    </div>
</section>

{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block title %} blog_detail {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog_detail {% endblock body_class %}
{% load static %}

{% block content %}
<!-- start section -->
<section class="one-fourth-screen bg-dark-gray ipad-top-space-margin sm-mb-50px" data-parallax-background-ratio="0.5" style="background-image: url({{ post.image.url }})">

</section>
<!-- end section -->
<!-- start section -->
<section class="p-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 overlap-section text-center">
                <div class="p-10 box-shadow-extra-large border-radius-4px bg-white text-center">
                    <a href="/" class="bg-solitude-blue text-uppercase fs-13 ps-25px pe-25px alt-font fw-500 text-base-color lh-40 sm-lh-55 border-radius-100px d-inline-block mb-3 sm-mb-15px">{{ post.category }}</a>
                    <h3 class="alt-font text-dark-gray fw-600 ls-minus-1px mb-15px">{{ post.title }}</h3>
                    <div class="lg-20px sm-mb-0">
                        <span><a href="/" class="text-dark-gray fw-700">Our Teams</a></span> were actively engaged on {{ post.date }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end section -->
<!-- start section -->
<section class="overlap-section text-center p-0 sm-pt-30px">
    <img class="rounded-circle box-shadow-extra-large w-130px h-130px border border-8 border-color-white" src="{%static 'assets/images/logo/outher.png' %}" alt="">
</section>
<!-- end section -->
<!-- start section -->
<section class="pb-0 pt-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9 dropcap-style-01" data-anime='{ "el": "childs", "translateY": [50, 0], "opacity": [0,1], "duration": 1200, "delay": 0, "staggervalue": 150, "easing": "easeOutQuad" }'>
                <p class="mb-6 text-center ">{{ post.subtitle }}</p>
                <div class="row">
                    <div class="col-12 sm-mb-30px">
                        <div class=" h-100 pt-8 pb-8 ps-10 pe-10 last-paragraph-no-margin">

                            <p>{{ post.content|safe }}</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- end section -->


{% endblock %}